apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-device-plugins-gpu
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: intel-device-plugins-gpu
      version: 0.32.1
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: kube-system
      interval: 12h
  values:
    name: intel-gpu-plugin
    sharedDevNum: 1 
    nodeSelector: {}
    tolerations: []
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
