apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: device-plugin-operator
  namespace: inteldeviceplugins-system
spec:
  interval: 30m
  chart:
    spec:
      chart: intel-device-plugins-operator
      version: 0.32.1
      sourceref:
        kind: helmrepository
        name: intel
        namespace: inteldeviceplugins-system
      interval: 12h
  values:
    manager:
      devices:
        gpu: true
