apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: intel
  namespace: kube-system
spec:
  interval: 12h
  url: https://intel.github.io/intel-device-plugins-for-kubernetes/charts/
