apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-env
  namespace: homepage
spec:
  secretStoreRef:
    name: aws-secretmanager
    kind: ClusterSecretStore
  target:
    name: homepage-env
  data:
    - secretKey: HOMEPAGE_ALLOWED_HOSTS
      remoteRef:
        key: homelab/homepage
        property: homepage-secret
