apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 30m
  chart:
    spec:
      chart: tailscale
      version: 1.84.3
      sourceRef:
        kind: HelmRepository
        name: tailscale-operator
        namespace: flux-system
      interval: 12h
  values:
    oauth:
      clientId: ""
      clientSecret: ""
  valuesFrom:
    - kind: Secret
      name: tailscale-clientid-secret
      valuesKey: clientId
      targetPath: oauth.clientId
    - kind: Secret
      name: tailscale-clientsecret-secret
      valuesKey: clientSecret
      targetPath: oauth.clientSecret
