apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 30m
  chart:
    spec:
      chart: tailscale
      version: 0.92.0
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
      interval: 12h
  values:
    tailscale:
      # Tailscale authentication key
      TS_AUTH_KEY: ""
      TS_TAGS: tag:vpn

    useDaemonSet: true
    nodeSelector:
      node-role.kubernetes.io/vpn: ""

    podSecurityContext:
      sysctls:
        - name: net.ipv6.conf.all.forwarding
          value: "1"
  valuesFrom:
    - kind: Secret
      name: tailscale-auth-secret
      valuesKey: TS_AUTH_KEY
      targetPath: tailscale.TS_AUTH_KEY
