apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-funnel
  namespace: jellyfin
  annotations:
    tailscale.com/funnel: "true"
    tailscale.com/hostname: "jellyfin"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: jellyfin  # Your Jellyfin service name
      port:
        number: 8096  # Jellyfin's port
  tls:
    - hosts:
        - jellyfin  # This becomes jellyfin.your-tailnet.ts.net
