apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 30m
  chart:
    spec:
      chart: jellyfin
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: jellyfin
      interval: 12h
  values:
    service:
      type: LoadBalancer
    podSecurityContext:
      fsGroup: 3000
    securityContext:
      capabilities:
        add:
          - "SYS_ADMIN"
        drop:
          - "ALL"
    volumes:
      - name: truenas-media
        nfs:
          server: 10.246.144.2
          path: /mnt/Bulk/media
      - name: hwa
        hostPath:
          path: /dev/dri
    volumeMounts:
      - name: truenas-media
        mountPath: /mnt/Bulk/media
      - name: hwa
        mountPath: /dev/dri
    persistence:
      config:
        storageClass: iscsi
        size: 10Gi
      media:
        enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: monitoring
    resources:
      limits:
        gpu.intel.com/i915: 1
      requests:
        gpu.intel.com/i915: 1
