apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 30m
  chart:
    spec:
      chart: jellyfin
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: jellyfin
      interval: 12h
  values:
    image:
      repository: ghcr.io/jellyfin/jellyfin
      tag: 10.11.2@sha256:749972be6e7d440a47531ee36c9e38ea7a6271c875f42e8a52851c39862b0773
    service:
      type: LoadBalancer
    podSecurityContext:
      fsGroup: 3000
    securityContext:
      privileged: true
    volumes:
      - name: truenas-media
        nfs:
          server: 10.246.144.2
          path: /mnt/Bulk/media
      - name: dri
        hostPath:
          path: /dev/dri/renderD128
    volumeMounts:
      - name: truenas-media
        mountPath: /mnt/Bulk/media
      - name: dri
        mountPath: /dev/dri/renderD128
    persistence:
      config:
        storageClass: iscsi
        size: 10Gi
      media:
        enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: monitoring
    resources:
      limits:
        gpu.intel.com/i915: 1
