apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 30m
  chart:
    spec:
      chart: jellyfin
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: jellyfin
      interval: 12h
  values:
    ingress:
      enabled: true
      className: tailscale
      annotations:
        tailscale.com/funnel: "true"
        tailscale.com/hostname: "jellyfin"
      tls:
        tls:
          - hosts:
              - jellyfin
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 3000
      fsGroup: 3000
      seccompProfile:
        type: RuntimeDefault
    securityContext:
      privileged: true
      allowPrivilegeEscalation: true
    volumes:
      - name: truenas-media
        nfs:
          server: 10.246.144.2
          path: /mnt/Bulk/k8s/nfs/media
      - name: gpu
        hostPath:
          path: /dev/dri/renderD128
    volumeMounts:
      - name: truenas-media
        mountPath: /mnt/Bulk/k8s/nfs/media
      - name: gpu
        mountPath: /dev/dri/renderD128
    persistence:
      config:
        storageClass: iscsi
        size: 10Gi
      media:
        enabled: false
    resources:
      limits:
        gpu.intel.com/i915: 1
