apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 30m
  chart:
    spec:
      chart: jellyfin
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: jellyfin
      interval: 12h
  values:
    service:
      type: LoadBalancer
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      supplementalGroups:
        - 122
      privileged: true
    volumes:
      - name: truenas-media
        nfs:
          server: 10.246.144.2
          path: /mnt/Bulk/media
    volumeMounts:
      - name: truenas-media
        mountPath: /mnt/Bulk/media
    persistence:
      config:
        storageClass: iscsi
        size: 10Gi
      cache:
        storageClass: iscsi
        size: 5Gi
      media:
        enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: monitoring
    resources:
      limits:
        gpu.intel.com/i915: 1
      requests:
        gpu.intel.com/i915: 1
