apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: 9.3.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h
  values:
    service:
      Type: LoadBalancer
      loadBalancerClass: tailscale
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: grafana
