apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: apps-pool
spec:
  blocks:
    - cidr: "192.168.4.200/32"
  serviceSelector:
    matchLabels:
      homelab/exposure: apps
---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: telemetry-pool
spec:
  blocks:
    - cidr: "192.168.4.201/32"
  serviceSelector:
    matchLabels:
      homelab/exposure: telemetry
