apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-pg
  namespace: n8n
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: n8n
      owner: n8n
      secret:
        name: n8n-db-secret
  postgresql:
  storage:
    storageClass: iscsi
    size: 32Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: n8n
  namespace: n8n
spec:
  name: n8n
  owner: n8n
  cluster:
    name: n8n-pg
