apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 30m
  chart:
    spec:
      chart: n8n
      version: 1.15.7
      sourceRef:
        kind: HelmRepository
        name: community-charts
        namespace: community-charts
      interval: 12h
  values:
    db:
      type: postgresdb
    externalPostgresql:
      host:
        valueFrom:
          secretKeyRef:
            name: n8n-secret
            key: DB_HOSTNAME
      database:
        valueFrom:
          secretKeyRef:
            name: n8n-secret
            key: DB_NAME
      username:
        valueFrom:
          secretKeyRef:
            name: n8n-secret
            key: DB_USERNAME
      password:
        valueFrom:
          secretKeyRef:
            name: n8n-secret
            key: DB_PASSWORD
    redis:
      enabled: true
    persistence:
      enabled: true
      storageClass: "iscsi"
    ingress:
      enabled: true
      className: "tailscale"
      annotations:
        tailscale.com/funnel: true
