apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-db-secret
  namespace: n8n
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: n8n-db-secret
  data:
    - secretKey: username
      remoteRef:
        key: n8n-db-secret
        property: username
    - secretKey: password
      remoteRef:
        key: n8n-db-secret
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-secret
  namespace: n8n
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: n8n-secret
  data:
    - secretKey: DB_HOSTNAME
      remoteRef:
        key: n8n
        property: DB_HOSTNAME
    - secretKey: DB_USERNAME
      remoteRef:
        key: n8n
        property: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: n8n
        property: DB_PASSWORD
    - secretKey: DB_NAME
      remoteRef:
        key: n8n
        property: DB_NAME
