apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: truenas-api-secret
  namespace: democratic-csi
spec:
  secretStoreRef:
    name: aws-secretmanager
    kind: ClusterSecretStore
  target:
    name: truenas-api-secret
  data:
    - secretKey: apiKey
      remoteRef:
        key: homelab/truenas-secret

