apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: democratic-csi
  namespace: flux-system
resources:
  - namespace.yaml
  - repository.yaml
  - iscsi/iscsi.yaml
  - nfs/nfs.yaml
