apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-db-secret
  namespace: immich
spec:
  secretStoreRef:
    name: aws-secretmanager
    kind: ClusterSecretStore
  target:
    name: homelab/truenas-secret
  data:
    - secretKey: truenas-api-secret
      remoteRef:
        key: apiKey
        property: truenas-api-secret

