apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
  labels:
    cilium-lb-pool: vault-pool
spec:
  type: LoadBalancer
  # no loadBalancerIP
  ports:
    - port: 8200
      targetPort: 8200
  selector:
    app: vault
