apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 30m
  chart:
    spec:
      chart: cert-manager
      version: 0.3*
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      interval: 12h
  values:
    global:
      enabled: true
      tlsDiable: false

    injector:
      enabled: true
      image:
        repository: "hashicorp/vault"
        tag: "latest"


      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "256Mi"
          cpu: "250m"

    server:

      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "500m"

      readinessProbe:
        enabled: true
        path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
      livenessProbe:
        enabled: true
        path: "/v1/sys/health?standbyok=true"
        initialDelaySeconds: 60

      auditStorage:
        enabled: true

        standalone:
          enabled: false

      extraSecretEnviromentVars:
        - envName: AWS_ACCESS_KEY_ID
          secretName: vault-aws-creds
          secretValue: AWS_ACCESS_KEY_ID
        - envName: AWS_SECRET_ACCESS_KEY_ID
          secretName: vault-aws-creds
          secretValue: AWS_SECRET_ACCESS_KEY_ID

      ha:
        enabled: true
        replicas: 3
        raft:
          enabled: true
          setNodeId: false
          config: |
            ui = true
            listener "tcp" {
              address = "[::]:8200"
              cluster_address = "[::]8201"
            }

            seal "awskms" {
              region = "us-west-2"
              kms_key_id = ""
            }

            storage "raft" {}

            service_registration "kubernetes" {}
            |
      tls:
        enabled: true
        secretName: vault-server-tls
    ui:
      enabled: true
      serviceType: "ClusterIP"
