apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-pg
  namespace: immich
spec:
  imageName: tensorchord/cloudnative-vectorchord:17-0.4.3
  instances: 2
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true
  superuserSecret:
    name: immich-db-secret
  bootstrap:
    initdb:
      database: immich
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  monitoring:
    enablePodMonitor: true
  storage:
    storageClass: iscsi
    size: 32Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich
  namespace: immich
spec:
  name: immich
  owner: immich
  cluster:
    name: immich-pg
