apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: "0.10.x"
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: immich
      interval: 12h
  values:
    controllers:
      main:
        containers:
          main:
            env:
              TZ: "America/Los_Angeles"
              DB_HOSTNAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-secret
                    key: DB_HOSTNAME
              DB_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-secret
                    key: DB_USERNAME
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-secret
                    key: DB_PASSWORD
              DB_DATABASE_NAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-secret
                    key: DB_DATABASE_NAME
    immich:
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim: immich-data
    valkey:
      enabled: true

    server:
      enabled: true
      controllers:
        main:
          containers:
            main:
              resources:
                limits:
                  gpu.intel.com/i915: 1
                requests:
                  gpu.intel.com/i915: 1
    machine-learning:
      enabled: true
      controllers:
        main:
          containers:
            main:
              resources:
                limits:
                  gpu.intel.com/i915: 1
                requests:
                  gpu.intel.com/i915: 1
