apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: "0.9.x"
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: monitoring
      interval: 12h
  values:
    service:
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: grafana
