apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-db-secret
  namespace: immich
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: immich-db-secret
  data:
    - secretKey: username
      remoteRef:
        key: immich-db
        property: username
    - secretKey: password
      remoteRef:
        key: immich-db
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-secret
  namespace: immich
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: immich-secret
  data:
    - secretKey: DB_HOSTNAME
      remoteRef:
        key: immich
        property: DB_HOSTNAME
    - secretKey: DB_USERNAME
      remoteRef:
        key: immich
        property: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: immich
        property: DB_PASSWORD
    - secretKey: DB_DATABASE_NAME
      remoteRef:
        key: immich
        property: DB_DATABASE_NAME
