apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: renovate/renovate:43.84.2
              args:
                - dokokisune/Homelab
              env:
                - name: dryRun
                  value: "full"
                - name: LOG_LEVEL
                  value: debug
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate-k8s-secret
                      key: RENOVATE_TOKEN
          restartPolicy: OnFailure
