apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-secret
  namespace: renovate
spec:
  secretStoreRef:
    name: aws-secretmanager
    kind: ClusterSecretStore
  target:
    name: renovate-k8s-secret
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: homelab/renovate
        property: RENOVATE_TOKEN
