# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 30m
  chart:
    spec:
      chart: istiod
      version: 1.28.1
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 12h
  install:
    timeout: 10m
    replace: true
    crds: CreateReplace
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
      strategy: rollback
    cleanupOnFail: true
    crds: CreateReplace
  values:
    global:
      meshID: home-mesh
      multiCluster:
        clusterName: cluster-main
      network: home-network
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-gateway
  namespace: istio-system
spec:
  interval: 30m
  dependsOn:
    - name: istiod
      namespace: istio-system
  chart:
    spec:
      chart: gateway
      version: 1.28.1
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 12h
  install:
    timeout: 10m
    replace: true
    crds: CreateReplace
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
      strategy: rollback
    cleanupOnFail: true
    crds: CreateReplace
  values:
    service:
      type: LoadBalancer
      ports:
        - name: tls-istiod
          port: 15012
          targetPort: 15012
        - name: tls-mesh
          port: 15443
          targetPort: 15443
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
