---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: democratic-csi-iscsi
  namespace: democratic-csi
spec:
  interval: 5m
  timeout: 15m
  chart:
    spec:
      chart: democratic-csi
      version: 0.15.0
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  values:
    controller:
      externalAttacher:
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
            ephemeral-storage: 100Mi
          limits:
            memory: 200Mi
            ephemeral-storage: 200Mi
      externalProvisioner:
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
            ephemeral-storage: 100Mi
          limits:
            memory: 200Mi
            ephemeral-storage: 200Mi
      externalResizer:
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
            ephemeral-storage: 100Mi
          limits:
            memory: 200Mi
            ephemeral-storage: 200Mi
      externalSnapshotter:
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
            ephemeral-storage: 100Mi
          limits:
            memory: 200Mi
            ephemeral-storage: 200Mi
      driver:
        image:
          registry: docker.io/democraticcsi/democratic-csi
          tag: next
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
              - SYS_ADMIN
            privileged: true
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
            ephemeral-storage: 100Mi
          limits:
            memory: 200Mi
            ephemeral-storage: 200Mi
    csiProxy:
      resources:
        requests:
          cpu: 10m
          memory: 50Mi
          ephemeral-storage: 100Mi
        limits:
          memory: 150Mi
          ephemeral-storage: 200Mi
    csiDriver:
      name: "org.democratic-csi.iscsi"
    storageClasses:
      - name: iscsi
        defaultClass: true
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: ext4
          detachedVolumesFromSnapshots: "false"
        mountOptions: []
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
          node-publish-secret:
          controller-expand-secret:
    driver:
      config:
        driver: freenas-api-iscsi
        instance_id:
        httpConnection:
          protocol: https
          host: 10.246.144.2
          port: 443
          allowInsecure: true
          path: /api/v2.0
          apiKey: ""
        zfs:
          datasetParentName: Bulk/k8s/iscsi/v
          detachedSnapshotsDatasetParentName: Bulk/k8s/iscsi/s
          zvolCompression:
          zvolDedup:
          zvolEnableReservation: false
          zvolBlocksize:
        iscsi:
          targetPortal: "10.246.144.2:3260"
          interface:
          namePrefix: csi-
          nameSuffix: "-cluster"
          targetGroups:
            - targetGroupPortalGroup: 1
              targetGroupInitiatorGroup: 1
              targetGroupAuthType: None
              targetGroupAuthGroup:
          extentInsecureTpc: true
          extentXenCompat: false
          extentDisablePhysicalBlocksize: true
          extentBlocksize: 512
          extentRpm: "SSD"
          extentAvailThreshold: 0
    node:
      hostPID: true
      driver:
        extraEnv:
          - name: ISCSIADM_HOST_STRATEGY
            value: nsenter
          - name: ISCSIADM_HOST_PATH
            value: /usr/local/sbin/iscsiadm
        iscsiDirHostPath: /var/iscsi
        iscsiDirHostPathType: ""
        resources:
          requests:
            cpu: 30m
            memory: 50Mi
            ephemeral-storage: 100Mi
          limits:
            memory: 200Mi
            ephemeral-storage: 200Mi
      driverRegistrar:
        resources:
          requests:
            cpu: 30m
            memory: 50Mi
            ephemeral-storage: 100Mi
          limits:
            memory: 200Mi
            ephemeral-storage: 200Mi
      cleanup:
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
            ephemeral-storage: 100Mi
          limits:
            memory: 200Mi
            ephemeral-storage: 200Mi
  valuesFrom:
    - kind: Secret
      name: truenas-api-secret
      valuesKey: apiKey
      targetPath: driver.config.httpConnection.apiKey
