---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: democratic-csi-nfs
  namespace: democratic-csi
spec:
  interval: 5m
  timeout: 15m
  chart:
    spec:
      chart: democratic-csi
      version: 0.15.0
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  values:
    existingConfigSecret: truenas-api-secret
    controller:
      externalAttacher:
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
            ephemeral-storage: 100Mi
          limits:
            memory: 100Mi
            ephemeral-storage: 200Mi
      externalProvisioner:
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
            ephemeral-storage: 100Mi
          limits:
            memory: 100Mi
            ephemeral-storage: 200Mi
      externalResizer:
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
            ephemeral-storage: 100Mi
          limits:
            memory: 100Mi
            ephemeral-storage: 200Mi
      externalSnapshotter:
        resources:
          requests:
            cpu: 10m
            memory: 30Mi
            ephemeral-storage: 100Mi
          limits:
            memory: 100Mi
            ephemeral-storage: 200Mi
      driver:
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
            ephemeral-storage: 100Mi
          limits:
            memory: 100Mi
            ephemeral-storage: 200Mi
    csiProxy:
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
          ephemeral-storage: 100Mi
        limits:
          memory: 100Mi
          ephemeral-storage: 200Mi
    csiDriver:
      name: "org.democratic-csi.nfs"
    storageClasses:
      - name: nfs
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: nfs
          detachedVolumesFromSnapshots: "false"
        mountOptions:
          - nfsvers=4.2
          - nconnect=8
          - hard
          - noatime
          - nodiratime
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
          node-publish-secret:
          controller-expand-secret:
    driver:
      config:
        driver: freenas-api-nfs
        instance_id:
        httpConnection:
          protocol: https
          host: 10.246.144.2
          port: 443
          allowInsecure: false
          apiKey: ""
        customCACertificates:
          - secret: truenas-https-tls
            key: ca.crt
        zfs:
          datasetParentName: mnt/Bulk/k8s/nfs/v
          detachedSnapshotsDatasetParentName: mnt/Bulk/k8s/nfs/s
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetPermissionsMode: "0777"
          datasetPermissionsUser: 0
          datasetPermissionsGroup: 0
        nfs:
          shareHost: 10.246.144.2
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: []
          shareMaprootUser: root
          shareMaprootGroup: root
          shareMapallUser: ""
          shareMapallGroup: ""
    node:
      driver:
        resources:
          requests:
            cpu: 30m
            memory: 100Mi
            ephemeral-storage: 100Mi
          limits:
            memory: 200Mi
            ephemeral-storage: 200Mi
      driverRegistrar:
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
            ephemeral-storage: 100Mi
          limits:
            memory: 200Mi
            ephemeral-storage: 200Mi
      cleanup:
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
            ephemeral-storage: 100Mi
          limits:
            memory: 200Mi
            ephemeral-storage: 200Mi
  valuesFrom:
    - kind: Secret
      name: truenas-api-secret
      valuesKey: apiKey
      targetPath: driver.config.httpConnection.apiKey
