apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-agent
  namespace: monitoring
spec:
  dependsOn:
    - name: opentelemetry-operator
  interval: 30m
  chart:
    spec:
      chart: opentelemetry-collector
      version: 0.143.0
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: monitoring
      interval: 12h
    values:
      mode: daemonset
      presets:
        logsCollection:
          enabled: true
        kubeletMetrics:
          enabled: true
      config:
        exporters:
          otlp:
            endpoint: "otel-gateway.monitoring.svc.cluster.local:4317"
            tls:
              insecure: true
        service:
          pipelines:
            metrics:
              exporters: [otlp]
            logs:
              exporters: [otlp]
            traces:
              exporters: [otlp]
