apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-gateway
  namespace: monitoring
spec:
  dependsOn:
    - name: open-telemetry-operator
  interval: 30m
  chart:
    spec:
      chart: opentelemetry-collector
      version: 0.147.1
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: monitoring
      interval: 12h
  values:
    mode: deployment
    image:
      repository: otel/opentelemetry-collector-contrib
    ports:
      otlp-external-grpc:
        enabled: true
        containerPort: 14317
        servicePort: 14317
        protocol: TCP
        appProtocol: kubernetes.io/h2c
      otlp-external-http:
        enabled: true
        containerPort: 14318
        servicePort: 14318
        protocol: TCP
    config:
      receivers:
        otlp/external:
          protocols:
            grpc:
              endpoint: ${env:MY_POD_IP}:14317
            http:
              endpoint: ${env:MY_POD_IP}:14318
      exporters:
        prometheusremotewrite:
          endpoint: "http://kube-prometheus-stack-prometheus:9090/api/v1/write"
          tls:
            insecure: true
        otlphttp/loki:
          endpoint: "http://loki:3100/otlp"
          tls:
            insecure: true
        otlp/tempo:
          endpoint: "tempo.monitoring.svc.cluster.local:4317"
          tls:
            insecure: true

      service:
        pipelines:
          metrics:
            receivers: [otlp, otlp/external]
            processors: [batch]
            exporters: [prometheusremotewrite]
          logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlphttp/loki]
          traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp/tempo]
