apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-gateway
  namespace: monitoring
spec:
  dependsOn:
    - name: open-telemetry-operator
  interval: 30m
  chart:
    spec:
      chart: opentelemetry-collector
      version: 0.143.0
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: monitoring
      interval: 12h
  values:
    mode: deployment
    image :
      repository: otel/opentelemetry-collector-contrib
    config:
      exporters:
        prometheusremotewrite:
          endpoint: "http://kube-prometheus-stack-prometheus:9090/api/v1/write"
          tls:
            insecure: true
        otlphttp/loki:
          endpoint: "http://loki:3100/otlp"
          tls:
            insecure: true
        otlp/tempo:
          endpoint: "http://tempo:3200"
          tls:
            insecure: true

      service:
        pipelines:
          metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [prometheusremotewrite]
          logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlphttp/loki]
          traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp/tempo]
