apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-gateway
  namespace: monitoring
spec:
  dependsOn:
    - name: opentelemetry-operator
  interval: 30m
  chart:
    spec:
      chart: opentelemetry-collector
      version: 0.143.0
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: monitoring
      interval: 12h
    values:
      mode: deployment
      clusterMetrics:
        enabled: true
