apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-telemetry-operator
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: opentelemetry-operator
      version: 0.102.0
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: monitoring
      interval: 12h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-telemetry-collector
  namespace: monitoring
spec:
  dependsOn:
    - name: opentelemetry-operator
  interval: 30m
  chart:
    spec:
      chart: opentelemetry-collector
      version: 0.143.0
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: monitoring
      interval: 12h

