apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-server-tls
  namespace: vault
spec:
  secretName: vault-server-tls
  issuerRef:
    name: selfsigned-ca
    kind: ClusterIssuer
  commonName: "vault-internal"
  dnsNames:
    - "vault-0.vault-internal"
    - "vault-1.vault-internal"
    - "vault-2.vault-internal"
    - "vault.vault.svc.cluster.local"
    - "vault-internal"
    - "localhost"
