apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-server-tls
  namespace: vault
spec:
  secretName: vault-server-tls
  issuerRef:
    name: internal-ca-issuer
    kind: ClusterIssuer
  commonName: "vault-internal"
  duration: 8760h
  renewBefore: 720h
  dnsNames:
    - "vault-0.vault-internal"
    - "vault-1.vault-internal"
    - "vault-2.vault-internal"
    - "vault.vault.svc.cluster.local"
    - "vault-active.vault.svc.cluster.local"
    - "vault-standby.vault.svc.cluster.local"
    - "vault-internal.vault.svc.cluster.local"
    - "vault-internal"
    - "localhost"
  ipAddresses:
    - "127.0.0.1"
  subject:
    organizationalUnits:
      - "Vault"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: actualbudget-cert
  namespace: actualbudget
spec:
  secretName: actualbudget-tls
  issuerRef:
    name: internal-ca-issuer       # your ClusterIssuer
    kind: ClusterIssuer
  dnsNames:
    - "actualbudget.local"
