apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-server-tls
  namespace: vault
spec:
  secretName: vault-server-tls
  issuerRef:
    name: internal-ca-issuer
    kind: ClusterIssuer
  commonName: "vault-internal"
  dnsNames:
    - "vault-0.vault-internal"
    - "vault-1.vault-internal"
    - "vault-2.vault-internal"
    - "vault.vault.svc.cluster.local"
    - "vault-internal"
    - "localhost"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: truenas-https-certificate
  namespace: democratic-csi
spec:
  secretName: truenas-https-tls
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: internal-ca-issuer
    kind: ClusterIssuer
  commonName: truenas.local
  dnsNames:
    - truenas.local
  ipAddresses:
    - "10.246.144.2"
