apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: actualbudget-cert
  namespace: actualbudget
spec:
  secretName: actualbudeget-secret
  issuerRef:
    name: internal-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - "actualbudget.local"
