apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actualbudget
  namespace: actualbudget
spec:
  interval: 30m
  chart:
    spec:
      chart: actualbudget
      version: "1.8.x"
      sourceRef:
        kind: HelmRepository
        name: community-charts
        namespace: flux-system
      interval: 12h
  values:
    persistence:
      enabled: true
      storageClass: "iscsi"

