apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  releaseName: external-secrets
  targetNamespace: external-secrets
  interval: 10m
  chart:
    spec:
      chart: external-secrets
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  values:
    webhook:
      lookaheadInterval: "1h"
      certManager:
        enabled: true
        addInjectorAnnotations: true
        cert:
          create: true
          issuerRef:
            group: cert-manager.io
            kind: "ClusterIssuer"
            name: "internal-ca-issuer"
          duration: "24h"
  upgrade:
    crds: CreateReplace
