apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secretmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            namespace: external-secrets
            name: awssm-credentials
            key: accessKeyID
          secretAccessKeySecretRef:
            namespace: external-secrets
            name: awssm-credentials
            key: secretAccessKey
