apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-gateway
  namespace: istio-system
spec:
  interval: 30m
  chart:
    spec:
      chart: gateway
      version: 1.28.1
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 12h
