apiVersion: v1
kind: Service
metadata:
  name: vault-ui
  namespace: vault
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: vault-ui
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/instance: vault
    component: server
  ports:
    - name: https
      port: 8200
      targetPort: 8200
